---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-dev-admin
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    apiGroup: ""
roleRef:
  kind: Role
  name: dev-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-dev-view
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
    apiGroup: ""
roleRef:
  kind: Role
  name: dev-view
  apiGroup: rbac.authorization.k8s.io
